import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
} from "docx";
import { slugify } from "@/lib/export/markdown";

/**
 * Convert a subset of markdown to a .docx file.
 *
 * Supported markdown subset (documented — anything outside this is treated
 * as plain text):
 *   - # / ## / ###                → Heading 1/2/3
 *   - **bold** and *italic*
 *   - - list items (flat, one level)
 *   - > blockquote
 *   - [link text](url)            → link text in italic (hyperlinks would
 *                                   need the ExternalHyperlink construct;
 *                                   omitted to keep this simple)
 *
 * Anything more advanced (tables, images, nested lists) is out of scope for
 * the PoC. Editors can always re-export as .md if they need full fidelity.
 */

export async function markdownToDocx(
  markdown: string,
  title: string,
): Promise<{ filename: string; buffer: Uint8Array }> {
  const lines = markdown.split(/\r?\n/);
  const paragraphs: Paragraph[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    // Blank line → skip (docx paragraphs already have spacing)
    if (line.trim() === "") continue;

    // Headings
    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: parseInline(line.slice(4)),
        }),
      );
      continue;
    }
    if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: parseInline(line.slice(3)),
        }),
      );
      continue;
    }
    if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.LEFT,
          children: parseInline(line.slice(2)),
        }),
      );
      continue;
    }

    // Blockquote
    if (line.startsWith("> ")) {
      paragraphs.push(
        new Paragraph({
          indent: { left: 720 },
          children: parseInline(line.slice(2), { forceItalic: true }),
        }),
      );
      continue;
    }

    // List item
    if (line.startsWith("- ") || line.startsWith("* ")) {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInline(line.slice(2)),
        }),
      );
      continue;
    }

    // Plain paragraph
    paragraphs.push(new Paragraph({ children: parseInline(line) }));
  }

  const doc = new Document({
    creator: "Atea CIO Analytics AI PoC",
    title,
    description: "Generated by CIO Analytics AI agents",
    sections: [{ children: paragraphs }],
  });

  const buffer = await Packer.toBuffer(doc);
  return {
    filename: `${slugify(title)}.docx`,
    buffer: new Uint8Array(buffer),
  };
}

/**
 * Parse inline **bold** and *italic* markers into TextRun objects.
 * Plain links [text](url) are rendered as "text (url)" plain text.
 * When forceItalic is true (e.g. inside a blockquote), every run gets
 * italics=true in addition to any inline styling.
 */
function parseInline(text: string, opts: { forceItalic?: boolean } = {}): TextRun[] {
  const forceItalic = opts.forceItalic ?? false;
  const runs: TextRun[] = [];
  // Strip markdown links first: [label](url) → "label (url)"
  const stripped = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)");

  // Tokenize **bold** and *italic*
  const tokenRegex = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
  let lastIndex = 0;
  const matches = stripped.matchAll(tokenRegex);
  for (const match of matches) {
    const idx = match.index ?? 0;
    if (idx > lastIndex) {
      runs.push(new TextRun({ text: stripped.slice(lastIndex, idx), italics: forceItalic }));
    }
    const token = match[0];
    if (token.startsWith("**")) {
      runs.push(new TextRun({ text: token.slice(2, -2), bold: true, italics: forceItalic }));
    } else {
      runs.push(new TextRun({ text: token.slice(1, -1), italics: true }));
    }
    lastIndex = idx + token.length;
  }
  if (lastIndex < stripped.length) {
    runs.push(new TextRun({ text: stripped.slice(lastIndex), italics: forceItalic }));
  }

  if (runs.length === 0) {
    runs.push(new TextRun({ text: stripped, italics: forceItalic }));
  }
  return runs;
}
